- instance_id: my-dsa-dataset.task-1
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-1
  problem_statement: ''
  before_repo_set_cmd: ''
- instance_id: my-dsa-dataset.task-10
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-10
  problem_statement: ''
  before_repo_set_cmd: ''
- instance_id: my-dsa-dataset.task-2
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-2
  problem_statement: ''
  before_repo_set_cmd: ''
- instance_id: my-dsa-dataset.task-3
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-3
  problem_statement: ''
  before_repo_set_cmd: ''
- instance_id: my-dsa-dataset.task-4
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-4
  problem_statement: ''
  before_repo_set_cmd: ''
- instance_id: my-dsa-dataset.task-5
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-5
  problem_statement: ''
  before_repo_set_cmd: ''
- instance_id: my-dsa-dataset.task-6
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-6
  problem_statement: ''
  before_repo_set_cmd: ''
- instance_id: my-dsa-dataset.task-7
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-7
  problem_statement: ''
  before_repo_set_cmd: ''
- instance_id: my-dsa-dataset.task-8
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-8
  problem_statement: ''
  before_repo_set_cmd: ''
- instance_id: my-dsa-dataset.task-9
  repo_name: my-dsa-dataset
  base_commit: ''
  image_name: akarti1102tyagi/anvil_project:my-dsa-dataset.task-9
  problem_statement: ''
  before_repo_set_cmd: ''
